project:
    type: default
    output-dir: docs

toc: true
toc-depth: 5
toc-location: right
number-sections: false
appendix-style: default
  
format:
    html:
        css: _extensions/biodoc/.style/_style.css
        html-math-method: katex

engine: knitr
brand: _brand.yml
    