::: {.content-hidden unless-meta="has-rating"}

:::{.hidden}

```{r}
#| output: false

points <- 0
max_points <- 0
level_1_points <- 0
level_2_points <- 0
level_3_points <- 0
level_1_max_points <- 0
level_2_max_points <- 0
level_3_max_points <- 0
level_1_total_points <- 0
level_2_total_points <- 0
level_3_total_points <- 0
total_points <- 0
level_1_multiplier <- 1
level_2_multiplier <- 2
level_3_multiplier <- 3

```

:::

## Arbeitsaufträge {.unnumbered}

Bevor Du loslegst, rufe Dir die [Anforderungen](https://mgmssa.github.io/bio_expectations_and_requirements/) für Biologieaufgaben in Stufe 10 ins Gedächtnis. Reiche die Antworten als digitales Dokument ein und verwende eine leserliche Schrift, falls Du ein handgeschriebenes Dokument einreichst. Stufe I ist auf E Niveau, Stufe II ist auf E/A Niveau, Stufe III ist komplett auf A Niveau angesiedelt. 

Die Grundpunktanzahl eines Arbeitsauftrages wird durch die Summe der Grundpunkte aller Aufgaben berechnet. Die Grundpunkte kannst Du nicht einsehen, weil sie für Dich bei der Wahl der Aufgaben keine Rolle spielen. Die Grundpunkte sind aber wichtig, weil die Benotungsstufen von ihnen abhängt.

Keine Panik! Die Grundpunkte werden mit den Multiplikatoren **1** für Stufe I, **2** für Stufe II, und **3** für Stufe III, multipliziert. Du bekommst *diese* Punkte und nicht die Grundpunkte. Du vergleichst *diese* Punkte mit der Tabelle, um Deine Note einzuschätzen. Das heisst, weil Deine Punkte durch die Multiplikatoren gegangen sind, kannst Du mehr Punkte einfahren, als zum Erreichen einer Notenstufe "Sehr gut" notwendig ist.
